name: Bug report
description: Use this template for reporting bugs.
labels: bug
body: 
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue. What is the expected behavior, and what is the actual behavior?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide the following details:
        - Operating System:
        - Browser (if applicable):
        - Python version (if applicable):
        - Other relevant software versions:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false