name: Feature request
description: Suggest a feature!
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        If you like to discuss your idea first, please join our [Slack](https://join.slack.com/t/dat-labs/shared_invite/zt-23wh57yhx-3kAdu022NJjabn8M25qTxA)
        and pose your questions in the `#technical-help` channel.
        For minor features and improvements, feel free to open a [pull request](https://github.com/dat-labs/dat-core/pulls) directly.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: >
        What would you like to happen?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you a dat user?
      description: Please tell us how you are using dat.
      multiple: false
      options:
        - "Yes, I'm already a dat user."
        - "Yes, I run dat in production."
        - "Yes, I use it for fun."
        - "I'd consider using dat, but it's lacking a feature I need."
        - "No, I don't use dat."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Is your feature request related to a problem? Please describe.
      placeholder: >
        What problem are you trying to solve?
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false