name: Feature request
description: Use this template for suggesting new features.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Suggestion
      description: A clear and concise description of what you want to happen
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false